spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movies
    driver: com.mysql.cj.jdbc.driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "useremail@gmail.com"
    password: "APP_PASSWORD"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        
server:
  port: 9090
  
project:
  poster: posters/

base:
  url: "http://localhost:9090"